gitops-runtime:
  argo-cd:
    enabled: false
  argo-workflows:
    controller:
      workflowDefaults:
        spec:
          archiveLogs: true
          artifactRepositoryRef:
            configMap: codefresh-workflows-log-store
            key: codefresh-workflows-log-store
  global:
    codefresh:
      accountId: 685180bf5bf52a8ffd9443ec
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    external-argo-cd:
      auth:
        type: token
        tokenSecretKeyRef:
          name: gitops-runtime-argo-cd-token
          key: token
    runtime:
      name: codefresh
      isConfigurationRuntime: true
