apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: guestbook
spec:
  project: default
  destination:
    name: in-cluster
    namespace: dev
  source:
    path: guestbook-demo/helm-guestbook-dev
    repoURL: https://github.com/idan-codefresh/gitops-cloud-demo-project.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
